name: dar_es_salaam
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  provider: ^4.3.2+1
  firebase_storage: ^4.0.0
  image_picker: ^0.6.7+7
  intl: ^0.16.1
  cached_network_image: ^2.3.1
  flutter_styled_toast: ^1.4.0+1
  modal_bottom_sheet: ^0.2.0+1
  animations: ^1.1.2
  search_page: ^1.3.0
  flutter_bounce: ^1.0.8
  flutter_email_sender: ^3.0.1
  extended_image: ^1.1.1
  flutter_staggered_grid_view: ^0.3.2
  adaptive_theme: ^1.0.0
  flutter_icons: ^1.1.0
  shared_preferences: ^0.5.12
  liquid_pull_to_refresh: ^2.0.0
  focused_menu: ^1.0.1
  expandable: ^4.1.4
  liquid_swipe: ^1.5.0
  flutter_progress_dialog: ^0.1.0
  after_layout: ^1.0.7+2
  random_color: ^1.0.5
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
  
